### ISSUE TITLE
Filters getting ignored after leaving a "Random Pick" Book

### ISSUE THREAD

**Issue by Eric-Philippe** [Eric-Philippe/GlitchAndBooks#1]
### Reproduce it -

- Apply one or more filters to the "Consulter" page
- Click on the "Pick Random" Book
- Erase the Search Bar
All the book are now here despite that the filters are still here

### Expected

- [x] When erasing the search bar from the random pick, keep using the applied filters

**Comment by Eric-Wahl** [comment]
Fixed on commit : [Fixing Issue](https://github.com/Eric-Philippe/GlitchAndBooks/commit/db690747ece71cc848e343c73c61604ef321324d) https://github.com/Eric-Philippe/GlitchAndBooks/issues/1 [- Bad behaviour Filters / Random Book](https://github.com/Eric-Philippe/GlitchAndBooks/commit/db690747ece71cc848e343c73c61604ef321324d)
