### ISSUE TITLE
The theme color for the types graph does not contain enough color for all the types

### ISSUE THREAD

**Issue by Eric-Philippe** [Eric-Philippe/GlitchAndBooks#4]
![image](https://github.com/Eric-Philippe/GlitchAndBooks/assets/66321178/8732a1f5-10bc-4148-aab2-e9c730e08042)

The theme provided by the Nivo library does not contains enough colors for all the types on the type graph
So we have to change to another one in order to have one color per type and not two types with the same color

**Comment by Eric-Wahl** [comment]
Fixed
